language: php

php:
  - 7.3
  - 7.4
  - master

branches:
  only:
    - 2.x

matrix:
  fast_finish: true
  allow_failures:
    - php: 'master'

sudo: required

before_script:
  - ulimit -c unlimited -S

before_install:
  - travis_retry sudo apt-get update -y
  - travis_retry sudo apt-get install -y lcov valgrind gdb
  - travis_retry gem install coveralls-lcov

script:
  - ./run-tests.sh normal
  - ./run-tests.sh coverage

after_success: ./run-tests.sh after_success

after_failure: ./run-tests.sh after_failure
